/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServidorRouteImport } from './routes/_authenticated/servidor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesTenantIdRouteImport } from './routes/_authenticated/clientes.$tenantId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedClientesTenantIdIndexRouteImport } from './routes/_authenticated/clientes.$tenantId.index'
import { Route as AuthenticatedClientesTenantIdUrasRouteImport } from './routes/_authenticated/clientes.$tenantId.uras'
import { Route as AuthenticatedClientesTenantIdTroncosRouteImport } from './routes/_authenticated/clientes.$tenantId.troncos'
import { Route as AuthenticatedClientesTenantIdRoteamentoRouteImport } from './routes/_authenticated/clientes.$tenantId.roteamento'
import { Route as AuthenticatedClientesTenantIdRegraHorarioRouteImport } from './routes/_authenticated/clientes.$tenantId.regra-horario'
import { Route as AuthenticatedClientesTenantIdRamaisRouteImport } from './routes/_authenticated/clientes.$tenantId.ramais'
import { Route as AuthenticatedClientesTenantIdNumerosRouteImport } from './routes/_authenticated/clientes.$tenantId.numeros'
import { Route as AuthenticatedClientesTenantIdHorarioRamaisRouteImport } from './routes/_authenticated/clientes.$tenantId.horario-ramais'
import { Route as AuthenticatedClientesTenantIdFilasRouteImport } from './routes/_authenticated/clientes.$tenantId.filas'
import { Route as AuthenticatedClientesTenantIdBlacklistRouteImport } from './routes/_authenticated/clientes.$tenantId.blacklist'
import { Route as AuthenticatedClientesTenantIdAudiosRouteImport } from './routes/_authenticated/clientes.$tenantId.audios'
import { Route as AuthenticatedClientesTenantIdRelatoriosUrasRouteImport } from './routes/_authenticated/clientes.$tenantId.relatorios.uras'
import { Route as AuthenticatedClientesTenantIdRelatoriosRamaisRouteImport } from './routes/_authenticated/clientes.$tenantId.relatorios.ramais'
import { Route as AuthenticatedClientesTenantIdRelatoriosPesquisaRouteImport } from './routes/_authenticated/clientes.$tenantId.relatorios.pesquisa'
import { Route as AuthenticatedClientesTenantIdRelatoriosFilasRouteImport } from './routes/_authenticated/clientes.$tenantId.relatorios.filas'
import { Route as AuthenticatedClientesTenantIdRelatoriosEntradaRouteImport } from './routes/_authenticated/clientes.$tenantId.relatorios.entrada'
import { Route as AuthenticatedClientesTenantIdRelatoriosDddRouteImport } from './routes/_authenticated/clientes.$tenantId.relatorios.ddd'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServidorRoute = AuthenticatedServidorRouteImport.update({
  id: '/servidor',
  path: '/servidor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesTenantIdRoute =
  AuthenticatedClientesTenantIdRouteImport.update({
    id: '/clientes/$tenantId',
    path: '/clientes/$tenantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesTenantIdIndexRoute =
  AuthenticatedClientesTenantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdUrasRoute =
  AuthenticatedClientesTenantIdUrasRouteImport.update({
    id: '/uras',
    path: '/uras',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdTroncosRoute =
  AuthenticatedClientesTenantIdTroncosRouteImport.update({
    id: '/troncos',
    path: '/troncos',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRoteamentoRoute =
  AuthenticatedClientesTenantIdRoteamentoRouteImport.update({
    id: '/roteamento',
    path: '/roteamento',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRegraHorarioRoute =
  AuthenticatedClientesTenantIdRegraHorarioRouteImport.update({
    id: '/regra-horario',
    path: '/regra-horario',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRamaisRoute =
  AuthenticatedClientesTenantIdRamaisRouteImport.update({
    id: '/ramais',
    path: '/ramais',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdNumerosRoute =
  AuthenticatedClientesTenantIdNumerosRouteImport.update({
    id: '/numeros',
    path: '/numeros',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdHorarioRamaisRoute =
  AuthenticatedClientesTenantIdHorarioRamaisRouteImport.update({
    id: '/horario-ramais',
    path: '/horario-ramais',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdFilasRoute =
  AuthenticatedClientesTenantIdFilasRouteImport.update({
    id: '/filas',
    path: '/filas',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdBlacklistRoute =
  AuthenticatedClientesTenantIdBlacklistRouteImport.update({
    id: '/blacklist',
    path: '/blacklist',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdAudiosRoute =
  AuthenticatedClientesTenantIdAudiosRouteImport.update({
    id: '/audios',
    path: '/audios',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRelatoriosUrasRoute =
  AuthenticatedClientesTenantIdRelatoriosUrasRouteImport.update({
    id: '/relatorios/uras',
    path: '/relatorios/uras',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRelatoriosRamaisRoute =
  AuthenticatedClientesTenantIdRelatoriosRamaisRouteImport.update({
    id: '/relatorios/ramais',
    path: '/relatorios/ramais',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRelatoriosPesquisaRoute =
  AuthenticatedClientesTenantIdRelatoriosPesquisaRouteImport.update({
    id: '/relatorios/pesquisa',
    path: '/relatorios/pesquisa',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRelatoriosFilasRoute =
  AuthenticatedClientesTenantIdRelatoriosFilasRouteImport.update({
    id: '/relatorios/filas',
    path: '/relatorios/filas',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRelatoriosEntradaRoute =
  AuthenticatedClientesTenantIdRelatoriosEntradaRouteImport.update({
    id: '/relatorios/entrada',
    path: '/relatorios/entrada',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)
const AuthenticatedClientesTenantIdRelatoriosDddRoute =
  AuthenticatedClientesTenantIdRelatoriosDddRouteImport.update({
    id: '/relatorios/ddd',
    path: '/relatorios/ddd',
    getParentRoute: () => AuthenticatedClientesTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/servidor': typeof AuthenticatedServidorRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clientes/$tenantId': typeof AuthenticatedClientesTenantIdRouteWithChildren
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/clientes/$tenantId/audios': typeof AuthenticatedClientesTenantIdAudiosRoute
  '/clientes/$tenantId/blacklist': typeof AuthenticatedClientesTenantIdBlacklistRoute
  '/clientes/$tenantId/filas': typeof AuthenticatedClientesTenantIdFilasRoute
  '/clientes/$tenantId/horario-ramais': typeof AuthenticatedClientesTenantIdHorarioRamaisRoute
  '/clientes/$tenantId/numeros': typeof AuthenticatedClientesTenantIdNumerosRoute
  '/clientes/$tenantId/ramais': typeof AuthenticatedClientesTenantIdRamaisRoute
  '/clientes/$tenantId/regra-horario': typeof AuthenticatedClientesTenantIdRegraHorarioRoute
  '/clientes/$tenantId/roteamento': typeof AuthenticatedClientesTenantIdRoteamentoRoute
  '/clientes/$tenantId/troncos': typeof AuthenticatedClientesTenantIdTroncosRoute
  '/clientes/$tenantId/uras': typeof AuthenticatedClientesTenantIdUrasRoute
  '/clientes/$tenantId/': typeof AuthenticatedClientesTenantIdIndexRoute
  '/clientes/$tenantId/relatorios/ddd': typeof AuthenticatedClientesTenantIdRelatoriosDddRoute
  '/clientes/$tenantId/relatorios/entrada': typeof AuthenticatedClientesTenantIdRelatoriosEntradaRoute
  '/clientes/$tenantId/relatorios/filas': typeof AuthenticatedClientesTenantIdRelatoriosFilasRoute
  '/clientes/$tenantId/relatorios/pesquisa': typeof AuthenticatedClientesTenantIdRelatoriosPesquisaRoute
  '/clientes/$tenantId/relatorios/ramais': typeof AuthenticatedClientesTenantIdRelatoriosRamaisRoute
  '/clientes/$tenantId/relatorios/uras': typeof AuthenticatedClientesTenantIdRelatoriosUrasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/servidor': typeof AuthenticatedServidorRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/clientes/$tenantId/audios': typeof AuthenticatedClientesTenantIdAudiosRoute
  '/clientes/$tenantId/blacklist': typeof AuthenticatedClientesTenantIdBlacklistRoute
  '/clientes/$tenantId/filas': typeof AuthenticatedClientesTenantIdFilasRoute
  '/clientes/$tenantId/horario-ramais': typeof AuthenticatedClientesTenantIdHorarioRamaisRoute
  '/clientes/$tenantId/numeros': typeof AuthenticatedClientesTenantIdNumerosRoute
  '/clientes/$tenantId/ramais': typeof AuthenticatedClientesTenantIdRamaisRoute
  '/clientes/$tenantId/regra-horario': typeof AuthenticatedClientesTenantIdRegraHorarioRoute
  '/clientes/$tenantId/roteamento': typeof AuthenticatedClientesTenantIdRoteamentoRoute
  '/clientes/$tenantId/troncos': typeof AuthenticatedClientesTenantIdTroncosRoute
  '/clientes/$tenantId/uras': typeof AuthenticatedClientesTenantIdUrasRoute
  '/clientes/$tenantId': typeof AuthenticatedClientesTenantIdIndexRoute
  '/clientes/$tenantId/relatorios/ddd': typeof AuthenticatedClientesTenantIdRelatoriosDddRoute
  '/clientes/$tenantId/relatorios/entrada': typeof AuthenticatedClientesTenantIdRelatoriosEntradaRoute
  '/clientes/$tenantId/relatorios/filas': typeof AuthenticatedClientesTenantIdRelatoriosFilasRoute
  '/clientes/$tenantId/relatorios/pesquisa': typeof AuthenticatedClientesTenantIdRelatoriosPesquisaRoute
  '/clientes/$tenantId/relatorios/ramais': typeof AuthenticatedClientesTenantIdRelatoriosRamaisRoute
  '/clientes/$tenantId/relatorios/uras': typeof AuthenticatedClientesTenantIdRelatoriosUrasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/servidor': typeof AuthenticatedServidorRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/clientes/$tenantId': typeof AuthenticatedClientesTenantIdRouteWithChildren
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/clientes/$tenantId/audios': typeof AuthenticatedClientesTenantIdAudiosRoute
  '/_authenticated/clientes/$tenantId/blacklist': typeof AuthenticatedClientesTenantIdBlacklistRoute
  '/_authenticated/clientes/$tenantId/filas': typeof AuthenticatedClientesTenantIdFilasRoute
  '/_authenticated/clientes/$tenantId/horario-ramais': typeof AuthenticatedClientesTenantIdHorarioRamaisRoute
  '/_authenticated/clientes/$tenantId/numeros': typeof AuthenticatedClientesTenantIdNumerosRoute
  '/_authenticated/clientes/$tenantId/ramais': typeof AuthenticatedClientesTenantIdRamaisRoute
  '/_authenticated/clientes/$tenantId/regra-horario': typeof AuthenticatedClientesTenantIdRegraHorarioRoute
  '/_authenticated/clientes/$tenantId/roteamento': typeof AuthenticatedClientesTenantIdRoteamentoRoute
  '/_authenticated/clientes/$tenantId/troncos': typeof AuthenticatedClientesTenantIdTroncosRoute
  '/_authenticated/clientes/$tenantId/uras': typeof AuthenticatedClientesTenantIdUrasRoute
  '/_authenticated/clientes/$tenantId/': typeof AuthenticatedClientesTenantIdIndexRoute
  '/_authenticated/clientes/$tenantId/relatorios/ddd': typeof AuthenticatedClientesTenantIdRelatoriosDddRoute
  '/_authenticated/clientes/$tenantId/relatorios/entrada': typeof AuthenticatedClientesTenantIdRelatoriosEntradaRoute
  '/_authenticated/clientes/$tenantId/relatorios/filas': typeof AuthenticatedClientesTenantIdRelatoriosFilasRoute
  '/_authenticated/clientes/$tenantId/relatorios/pesquisa': typeof AuthenticatedClientesTenantIdRelatoriosPesquisaRoute
  '/_authenticated/clientes/$tenantId/relatorios/ramais': typeof AuthenticatedClientesTenantIdRelatoriosRamaisRoute
  '/_authenticated/clientes/$tenantId/relatorios/uras': typeof AuthenticatedClientesTenantIdRelatoriosUrasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/servidor'
    | '/admin/usuarios'
    | '/clientes/$tenantId'
    | '/clientes/'
    | '/clientes/$tenantId/audios'
    | '/clientes/$tenantId/blacklist'
    | '/clientes/$tenantId/filas'
    | '/clientes/$tenantId/horario-ramais'
    | '/clientes/$tenantId/numeros'
    | '/clientes/$tenantId/ramais'
    | '/clientes/$tenantId/regra-horario'
    | '/clientes/$tenantId/roteamento'
    | '/clientes/$tenantId/troncos'
    | '/clientes/$tenantId/uras'
    | '/clientes/$tenantId/'
    | '/clientes/$tenantId/relatorios/ddd'
    | '/clientes/$tenantId/relatorios/entrada'
    | '/clientes/$tenantId/relatorios/filas'
    | '/clientes/$tenantId/relatorios/pesquisa'
    | '/clientes/$tenantId/relatorios/ramais'
    | '/clientes/$tenantId/relatorios/uras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/servidor'
    | '/admin/usuarios'
    | '/clientes'
    | '/clientes/$tenantId/audios'
    | '/clientes/$tenantId/blacklist'
    | '/clientes/$tenantId/filas'
    | '/clientes/$tenantId/horario-ramais'
    | '/clientes/$tenantId/numeros'
    | '/clientes/$tenantId/ramais'
    | '/clientes/$tenantId/regra-horario'
    | '/clientes/$tenantId/roteamento'
    | '/clientes/$tenantId/troncos'
    | '/clientes/$tenantId/uras'
    | '/clientes/$tenantId'
    | '/clientes/$tenantId/relatorios/ddd'
    | '/clientes/$tenantId/relatorios/entrada'
    | '/clientes/$tenantId/relatorios/filas'
    | '/clientes/$tenantId/relatorios/pesquisa'
    | '/clientes/$tenantId/relatorios/ramais'
    | '/clientes/$tenantId/relatorios/uras'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/servidor'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/clientes/$tenantId'
    | '/_authenticated/clientes/'
    | '/_authenticated/clientes/$tenantId/audios'
    | '/_authenticated/clientes/$tenantId/blacklist'
    | '/_authenticated/clientes/$tenantId/filas'
    | '/_authenticated/clientes/$tenantId/horario-ramais'
    | '/_authenticated/clientes/$tenantId/numeros'
    | '/_authenticated/clientes/$tenantId/ramais'
    | '/_authenticated/clientes/$tenantId/regra-horario'
    | '/_authenticated/clientes/$tenantId/roteamento'
    | '/_authenticated/clientes/$tenantId/troncos'
    | '/_authenticated/clientes/$tenantId/uras'
    | '/_authenticated/clientes/$tenantId/'
    | '/_authenticated/clientes/$tenantId/relatorios/ddd'
    | '/_authenticated/clientes/$tenantId/relatorios/entrada'
    | '/_authenticated/clientes/$tenantId/relatorios/filas'
    | '/_authenticated/clientes/$tenantId/relatorios/pesquisa'
    | '/_authenticated/clientes/$tenantId/relatorios/ramais'
    | '/_authenticated/clientes/$tenantId/relatorios/uras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servidor': {
      id: '/_authenticated/servidor'
      path: '/servidor'
      fullPath: '/servidor'
      preLoaderRoute: typeof AuthenticatedServidorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$tenantId': {
      id: '/_authenticated/clientes/$tenantId'
      path: '/clientes/$tenantId'
      fullPath: '/clientes/$tenantId'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$tenantId/': {
      id: '/_authenticated/clientes/$tenantId/'
      path: '/'
      fullPath: '/clientes/$tenantId/'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdIndexRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/uras': {
      id: '/_authenticated/clientes/$tenantId/uras'
      path: '/uras'
      fullPath: '/clientes/$tenantId/uras'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdUrasRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/troncos': {
      id: '/_authenticated/clientes/$tenantId/troncos'
      path: '/troncos'
      fullPath: '/clientes/$tenantId/troncos'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdTroncosRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/roteamento': {
      id: '/_authenticated/clientes/$tenantId/roteamento'
      path: '/roteamento'
      fullPath: '/clientes/$tenantId/roteamento'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRoteamentoRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/regra-horario': {
      id: '/_authenticated/clientes/$tenantId/regra-horario'
      path: '/regra-horario'
      fullPath: '/clientes/$tenantId/regra-horario'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRegraHorarioRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/ramais': {
      id: '/_authenticated/clientes/$tenantId/ramais'
      path: '/ramais'
      fullPath: '/clientes/$tenantId/ramais'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRamaisRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/numeros': {
      id: '/_authenticated/clientes/$tenantId/numeros'
      path: '/numeros'
      fullPath: '/clientes/$tenantId/numeros'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdNumerosRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/horario-ramais': {
      id: '/_authenticated/clientes/$tenantId/horario-ramais'
      path: '/horario-ramais'
      fullPath: '/clientes/$tenantId/horario-ramais'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdHorarioRamaisRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/filas': {
      id: '/_authenticated/clientes/$tenantId/filas'
      path: '/filas'
      fullPath: '/clientes/$tenantId/filas'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdFilasRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/blacklist': {
      id: '/_authenticated/clientes/$tenantId/blacklist'
      path: '/blacklist'
      fullPath: '/clientes/$tenantId/blacklist'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdBlacklistRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/audios': {
      id: '/_authenticated/clientes/$tenantId/audios'
      path: '/audios'
      fullPath: '/clientes/$tenantId/audios'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdAudiosRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/relatorios/uras': {
      id: '/_authenticated/clientes/$tenantId/relatorios/uras'
      path: '/relatorios/uras'
      fullPath: '/clientes/$tenantId/relatorios/uras'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRelatoriosUrasRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/relatorios/ramais': {
      id: '/_authenticated/clientes/$tenantId/relatorios/ramais'
      path: '/relatorios/ramais'
      fullPath: '/clientes/$tenantId/relatorios/ramais'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRelatoriosRamaisRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/relatorios/pesquisa': {
      id: '/_authenticated/clientes/$tenantId/relatorios/pesquisa'
      path: '/relatorios/pesquisa'
      fullPath: '/clientes/$tenantId/relatorios/pesquisa'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRelatoriosPesquisaRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/relatorios/filas': {
      id: '/_authenticated/clientes/$tenantId/relatorios/filas'
      path: '/relatorios/filas'
      fullPath: '/clientes/$tenantId/relatorios/filas'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRelatoriosFilasRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/relatorios/entrada': {
      id: '/_authenticated/clientes/$tenantId/relatorios/entrada'
      path: '/relatorios/entrada'
      fullPath: '/clientes/$tenantId/relatorios/entrada'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRelatoriosEntradaRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
    '/_authenticated/clientes/$tenantId/relatorios/ddd': {
      id: '/_authenticated/clientes/$tenantId/relatorios/ddd'
      path: '/relatorios/ddd'
      fullPath: '/clientes/$tenantId/relatorios/ddd'
      preLoaderRoute: typeof AuthenticatedClientesTenantIdRelatoriosDddRouteImport
      parentRoute: typeof AuthenticatedClientesTenantIdRoute
    }
  }
}

interface AuthenticatedClientesTenantIdRouteChildren {
  AuthenticatedClientesTenantIdAudiosRoute: typeof AuthenticatedClientesTenantIdAudiosRoute
  AuthenticatedClientesTenantIdBlacklistRoute: typeof AuthenticatedClientesTenantIdBlacklistRoute
  AuthenticatedClientesTenantIdFilasRoute: typeof AuthenticatedClientesTenantIdFilasRoute
  AuthenticatedClientesTenantIdHorarioRamaisRoute: typeof AuthenticatedClientesTenantIdHorarioRamaisRoute
  AuthenticatedClientesTenantIdNumerosRoute: typeof AuthenticatedClientesTenantIdNumerosRoute
  AuthenticatedClientesTenantIdRamaisRoute: typeof AuthenticatedClientesTenantIdRamaisRoute
  AuthenticatedClientesTenantIdRegraHorarioRoute: typeof AuthenticatedClientesTenantIdRegraHorarioRoute
  AuthenticatedClientesTenantIdRoteamentoRoute: typeof AuthenticatedClientesTenantIdRoteamentoRoute
  AuthenticatedClientesTenantIdTroncosRoute: typeof AuthenticatedClientesTenantIdTroncosRoute
  AuthenticatedClientesTenantIdUrasRoute: typeof AuthenticatedClientesTenantIdUrasRoute
  AuthenticatedClientesTenantIdIndexRoute: typeof AuthenticatedClientesTenantIdIndexRoute
  AuthenticatedClientesTenantIdRelatoriosDddRoute: typeof AuthenticatedClientesTenantIdRelatoriosDddRoute
  AuthenticatedClientesTenantIdRelatoriosEntradaRoute: typeof AuthenticatedClientesTenantIdRelatoriosEntradaRoute
  AuthenticatedClientesTenantIdRelatoriosFilasRoute: typeof AuthenticatedClientesTenantIdRelatoriosFilasRoute
  AuthenticatedClientesTenantIdRelatoriosPesquisaRoute: typeof AuthenticatedClientesTenantIdRelatoriosPesquisaRoute
  AuthenticatedClientesTenantIdRelatoriosRamaisRoute: typeof AuthenticatedClientesTenantIdRelatoriosRamaisRoute
  AuthenticatedClientesTenantIdRelatoriosUrasRoute: typeof AuthenticatedClientesTenantIdRelatoriosUrasRoute
}

const AuthenticatedClientesTenantIdRouteChildren: AuthenticatedClientesTenantIdRouteChildren =
  {
    AuthenticatedClientesTenantIdAudiosRoute:
      AuthenticatedClientesTenantIdAudiosRoute,
    AuthenticatedClientesTenantIdBlacklistRoute:
      AuthenticatedClientesTenantIdBlacklistRoute,
    AuthenticatedClientesTenantIdFilasRoute:
      AuthenticatedClientesTenantIdFilasRoute,
    AuthenticatedClientesTenantIdHorarioRamaisRoute:
      AuthenticatedClientesTenantIdHorarioRamaisRoute,
    AuthenticatedClientesTenantIdNumerosRoute:
      AuthenticatedClientesTenantIdNumerosRoute,
    AuthenticatedClientesTenantIdRamaisRoute:
      AuthenticatedClientesTenantIdRamaisRoute,
    AuthenticatedClientesTenantIdRegraHorarioRoute:
      AuthenticatedClientesTenantIdRegraHorarioRoute,
    AuthenticatedClientesTenantIdRoteamentoRoute:
      AuthenticatedClientesTenantIdRoteamentoRoute,
    AuthenticatedClientesTenantIdTroncosRoute:
      AuthenticatedClientesTenantIdTroncosRoute,
    AuthenticatedClientesTenantIdUrasRoute:
      AuthenticatedClientesTenantIdUrasRoute,
    AuthenticatedClientesTenantIdIndexRoute:
      AuthenticatedClientesTenantIdIndexRoute,
    AuthenticatedClientesTenantIdRelatoriosDddRoute:
      AuthenticatedClientesTenantIdRelatoriosDddRoute,
    AuthenticatedClientesTenantIdRelatoriosEntradaRoute:
      AuthenticatedClientesTenantIdRelatoriosEntradaRoute,
    AuthenticatedClientesTenantIdRelatoriosFilasRoute:
      AuthenticatedClientesTenantIdRelatoriosFilasRoute,
    AuthenticatedClientesTenantIdRelatoriosPesquisaRoute:
      AuthenticatedClientesTenantIdRelatoriosPesquisaRoute,
    AuthenticatedClientesTenantIdRelatoriosRamaisRoute:
      AuthenticatedClientesTenantIdRelatoriosRamaisRoute,
    AuthenticatedClientesTenantIdRelatoriosUrasRoute:
      AuthenticatedClientesTenantIdRelatoriosUrasRoute,
  }

const AuthenticatedClientesTenantIdRouteWithChildren =
  AuthenticatedClientesTenantIdRoute._addFileChildren(
    AuthenticatedClientesTenantIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedServidorRoute: typeof AuthenticatedServidorRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedClientesTenantIdRoute: typeof AuthenticatedClientesTenantIdRouteWithChildren
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedServidorRoute: AuthenticatedServidorRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedClientesTenantIdRoute:
    AuthenticatedClientesTenantIdRouteWithChildren,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
