/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RamalRouteImport } from './routes/ramal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated/cliente.index'
import { Route as AuthenticatedClienteUrasRouteImport } from './routes/_authenticated/cliente.uras'
import { Route as AuthenticatedClienteTroncosRouteImport } from './routes/_authenticated/cliente.troncos'
import { Route as AuthenticatedClienteRoteamentoRouteImport } from './routes/_authenticated/cliente.roteamento'
import { Route as AuthenticatedClienteRegraHorarioRouteImport } from './routes/_authenticated/cliente.regra-horario'
import { Route as AuthenticatedClienteRamaisRouteImport } from './routes/_authenticated/cliente.ramais'
import { Route as AuthenticatedClientePesquisaSatisfacaoRouteImport } from './routes/_authenticated/cliente.pesquisa-satisfacao'
import { Route as AuthenticatedClienteHorarioRamaisRouteImport } from './routes/_authenticated/cliente.horario-ramais'
import { Route as AuthenticatedClienteFilasRouteImport } from './routes/_authenticated/cliente.filas'
import { Route as AuthenticatedClienteBlacklistRouteImport } from './routes/_authenticated/cliente.blacklist'
import { Route as AuthenticatedClienteAudiosRouteImport } from './routes/_authenticated/cliente.audios'
import { Route as AuthenticatedAdminWhitelistRouteImport } from './routes/_authenticated/admin.whitelist'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminServidorRouteImport } from './routes/_authenticated/admin.servidor'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminBlacklistRouteImport } from './routes/_authenticated/admin.blacklist'
import { Route as AuthenticatedClienteRelatoriosUrasRouteImport } from './routes/_authenticated/cliente.relatorios.uras'
import { Route as AuthenticatedClienteRelatoriosPesquisaRouteImport } from './routes/_authenticated/cliente.relatorios.pesquisa'
import { Route as AuthenticatedClienteRelatoriosGeralRouteImport } from './routes/_authenticated/cliente.relatorios.geral'
import { Route as AuthenticatedClienteRelatoriosFilasRouteImport } from './routes/_authenticated/cliente.relatorios.filas'
import { Route as AuthenticatedClienteRelatoriosDddRouteImport } from './routes/_authenticated/cliente.relatorios.ddd'

const RamalRoute = RamalRouteImport.update({
  id: '/ramal',
  path: '/ramal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteUrasRoute =
  AuthenticatedClienteUrasRouteImport.update({
    id: '/uras',
    path: '/uras',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteTroncosRoute =
  AuthenticatedClienteTroncosRouteImport.update({
    id: '/troncos',
    path: '/troncos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteRoteamentoRoute =
  AuthenticatedClienteRoteamentoRouteImport.update({
    id: '/roteamento',
    path: '/roteamento',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteRegraHorarioRoute =
  AuthenticatedClienteRegraHorarioRouteImport.update({
    id: '/regra-horario',
    path: '/regra-horario',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteRamaisRoute =
  AuthenticatedClienteRamaisRouteImport.update({
    id: '/ramais',
    path: '/ramais',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePesquisaSatisfacaoRoute =
  AuthenticatedClientePesquisaSatisfacaoRouteImport.update({
    id: '/pesquisa-satisfacao',
    path: '/pesquisa-satisfacao',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteHorarioRamaisRoute =
  AuthenticatedClienteHorarioRamaisRouteImport.update({
    id: '/horario-ramais',
    path: '/horario-ramais',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteFilasRoute =
  AuthenticatedClienteFilasRouteImport.update({
    id: '/filas',
    path: '/filas',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteBlacklistRoute =
  AuthenticatedClienteBlacklistRouteImport.update({
    id: '/blacklist',
    path: '/blacklist',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteAudiosRoute =
  AuthenticatedClienteAudiosRouteImport.update({
    id: '/audios',
    path: '/audios',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminWhitelistRoute =
  AuthenticatedAdminWhitelistRouteImport.update({
    id: '/admin/whitelist',
    path: '/admin/whitelist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServidorRoute =
  AuthenticatedAdminServidorRouteImport.update({
    id: '/admin/servidor',
    path: '/admin/servidor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlacklistRoute =
  AuthenticatedAdminBlacklistRouteImport.update({
    id: '/admin/blacklist',
    path: '/admin/blacklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteRelatoriosUrasRoute =
  AuthenticatedClienteRelatoriosUrasRouteImport.update({
    id: '/relatorios/uras',
    path: '/relatorios/uras',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteRelatoriosPesquisaRoute =
  AuthenticatedClienteRelatoriosPesquisaRouteImport.update({
    id: '/relatorios/pesquisa',
    path: '/relatorios/pesquisa',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteRelatoriosGeralRoute =
  AuthenticatedClienteRelatoriosGeralRouteImport.update({
    id: '/relatorios/geral',
    path: '/relatorios/geral',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteRelatoriosFilasRoute =
  AuthenticatedClienteRelatoriosFilasRouteImport.update({
    id: '/relatorios/filas',
    path: '/relatorios/filas',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteRelatoriosDddRoute =
  AuthenticatedClienteRelatoriosDddRouteImport.update({
    id: '/relatorios/ddd',
    path: '/relatorios/ddd',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ramal': typeof RamalRoute
  '/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/blacklist': typeof AuthenticatedAdminBlacklistRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/servidor': typeof AuthenticatedAdminServidorRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/whitelist': typeof AuthenticatedAdminWhitelistRoute
  '/cliente/audios': typeof AuthenticatedClienteAudiosRoute
  '/cliente/blacklist': typeof AuthenticatedClienteBlacklistRoute
  '/cliente/filas': typeof AuthenticatedClienteFilasRoute
  '/cliente/horario-ramais': typeof AuthenticatedClienteHorarioRamaisRoute
  '/cliente/pesquisa-satisfacao': typeof AuthenticatedClientePesquisaSatisfacaoRoute
  '/cliente/ramais': typeof AuthenticatedClienteRamaisRoute
  '/cliente/regra-horario': typeof AuthenticatedClienteRegraHorarioRoute
  '/cliente/roteamento': typeof AuthenticatedClienteRoteamentoRoute
  '/cliente/troncos': typeof AuthenticatedClienteTroncosRoute
  '/cliente/uras': typeof AuthenticatedClienteUrasRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/cliente/relatorios/ddd': typeof AuthenticatedClienteRelatoriosDddRoute
  '/cliente/relatorios/filas': typeof AuthenticatedClienteRelatoriosFilasRoute
  '/cliente/relatorios/geral': typeof AuthenticatedClienteRelatoriosGeralRoute
  '/cliente/relatorios/pesquisa': typeof AuthenticatedClienteRelatoriosPesquisaRoute
  '/cliente/relatorios/uras': typeof AuthenticatedClienteRelatoriosUrasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ramal': typeof RamalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/blacklist': typeof AuthenticatedAdminBlacklistRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/servidor': typeof AuthenticatedAdminServidorRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/whitelist': typeof AuthenticatedAdminWhitelistRoute
  '/cliente/audios': typeof AuthenticatedClienteAudiosRoute
  '/cliente/blacklist': typeof AuthenticatedClienteBlacklistRoute
  '/cliente/filas': typeof AuthenticatedClienteFilasRoute
  '/cliente/horario-ramais': typeof AuthenticatedClienteHorarioRamaisRoute
  '/cliente/pesquisa-satisfacao': typeof AuthenticatedClientePesquisaSatisfacaoRoute
  '/cliente/ramais': typeof AuthenticatedClienteRamaisRoute
  '/cliente/regra-horario': typeof AuthenticatedClienteRegraHorarioRoute
  '/cliente/roteamento': typeof AuthenticatedClienteRoteamentoRoute
  '/cliente/troncos': typeof AuthenticatedClienteTroncosRoute
  '/cliente/uras': typeof AuthenticatedClienteUrasRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/cliente/relatorios/ddd': typeof AuthenticatedClienteRelatoriosDddRoute
  '/cliente/relatorios/filas': typeof AuthenticatedClienteRelatoriosFilasRoute
  '/cliente/relatorios/geral': typeof AuthenticatedClienteRelatoriosGeralRoute
  '/cliente/relatorios/pesquisa': typeof AuthenticatedClienteRelatoriosPesquisaRoute
  '/cliente/relatorios/uras': typeof AuthenticatedClienteRelatoriosUrasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ramal': typeof RamalRoute
  '/_authenticated/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/blacklist': typeof AuthenticatedAdminBlacklistRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/servidor': typeof AuthenticatedAdminServidorRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/whitelist': typeof AuthenticatedAdminWhitelistRoute
  '/_authenticated/cliente/audios': typeof AuthenticatedClienteAudiosRoute
  '/_authenticated/cliente/blacklist': typeof AuthenticatedClienteBlacklistRoute
  '/_authenticated/cliente/filas': typeof AuthenticatedClienteFilasRoute
  '/_authenticated/cliente/horario-ramais': typeof AuthenticatedClienteHorarioRamaisRoute
  '/_authenticated/cliente/pesquisa-satisfacao': typeof AuthenticatedClientePesquisaSatisfacaoRoute
  '/_authenticated/cliente/ramais': typeof AuthenticatedClienteRamaisRoute
  '/_authenticated/cliente/regra-horario': typeof AuthenticatedClienteRegraHorarioRoute
  '/_authenticated/cliente/roteamento': typeof AuthenticatedClienteRoteamentoRoute
  '/_authenticated/cliente/troncos': typeof AuthenticatedClienteTroncosRoute
  '/_authenticated/cliente/uras': typeof AuthenticatedClienteUrasRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/cliente/relatorios/ddd': typeof AuthenticatedClienteRelatoriosDddRoute
  '/_authenticated/cliente/relatorios/filas': typeof AuthenticatedClienteRelatoriosFilasRoute
  '/_authenticated/cliente/relatorios/geral': typeof AuthenticatedClienteRelatoriosGeralRoute
  '/_authenticated/cliente/relatorios/pesquisa': typeof AuthenticatedClienteRelatoriosPesquisaRoute
  '/_authenticated/cliente/relatorios/uras': typeof AuthenticatedClienteRelatoriosUrasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ramal'
    | '/cliente'
    | '/dashboard'
    | '/admin/blacklist'
    | '/admin/configuracoes'
    | '/admin/servidor'
    | '/admin/usuarios'
    | '/admin/whitelist'
    | '/cliente/audios'
    | '/cliente/blacklist'
    | '/cliente/filas'
    | '/cliente/horario-ramais'
    | '/cliente/pesquisa-satisfacao'
    | '/cliente/ramais'
    | '/cliente/regra-horario'
    | '/cliente/roteamento'
    | '/cliente/troncos'
    | '/cliente/uras'
    | '/cliente/'
    | '/clientes/'
    | '/cliente/relatorios/ddd'
    | '/cliente/relatorios/filas'
    | '/cliente/relatorios/geral'
    | '/cliente/relatorios/pesquisa'
    | '/cliente/relatorios/uras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ramal'
    | '/dashboard'
    | '/admin/blacklist'
    | '/admin/configuracoes'
    | '/admin/servidor'
    | '/admin/usuarios'
    | '/admin/whitelist'
    | '/cliente/audios'
    | '/cliente/blacklist'
    | '/cliente/filas'
    | '/cliente/horario-ramais'
    | '/cliente/pesquisa-satisfacao'
    | '/cliente/ramais'
    | '/cliente/regra-horario'
    | '/cliente/roteamento'
    | '/cliente/troncos'
    | '/cliente/uras'
    | '/cliente'
    | '/clientes'
    | '/cliente/relatorios/ddd'
    | '/cliente/relatorios/filas'
    | '/cliente/relatorios/geral'
    | '/cliente/relatorios/pesquisa'
    | '/cliente/relatorios/uras'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ramal'
    | '/_authenticated/cliente'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/blacklist'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/servidor'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/whitelist'
    | '/_authenticated/cliente/audios'
    | '/_authenticated/cliente/blacklist'
    | '/_authenticated/cliente/filas'
    | '/_authenticated/cliente/horario-ramais'
    | '/_authenticated/cliente/pesquisa-satisfacao'
    | '/_authenticated/cliente/ramais'
    | '/_authenticated/cliente/regra-horario'
    | '/_authenticated/cliente/roteamento'
    | '/_authenticated/cliente/troncos'
    | '/_authenticated/cliente/uras'
    | '/_authenticated/cliente/'
    | '/_authenticated/clientes/'
    | '/_authenticated/cliente/relatorios/ddd'
    | '/_authenticated/cliente/relatorios/filas'
    | '/_authenticated/cliente/relatorios/geral'
    | '/_authenticated/cliente/relatorios/pesquisa'
    | '/_authenticated/cliente/relatorios/uras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RamalRoute: typeof RamalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ramal': {
      id: '/ramal'
      path: '/ramal'
      fullPath: '/ramal'
      preLoaderRoute: typeof RamalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/uras': {
      id: '/_authenticated/cliente/uras'
      path: '/uras'
      fullPath: '/cliente/uras'
      preLoaderRoute: typeof AuthenticatedClienteUrasRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/troncos': {
      id: '/_authenticated/cliente/troncos'
      path: '/troncos'
      fullPath: '/cliente/troncos'
      preLoaderRoute: typeof AuthenticatedClienteTroncosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/roteamento': {
      id: '/_authenticated/cliente/roteamento'
      path: '/roteamento'
      fullPath: '/cliente/roteamento'
      preLoaderRoute: typeof AuthenticatedClienteRoteamentoRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/regra-horario': {
      id: '/_authenticated/cliente/regra-horario'
      path: '/regra-horario'
      fullPath: '/cliente/regra-horario'
      preLoaderRoute: typeof AuthenticatedClienteRegraHorarioRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/ramais': {
      id: '/_authenticated/cliente/ramais'
      path: '/ramais'
      fullPath: '/cliente/ramais'
      preLoaderRoute: typeof AuthenticatedClienteRamaisRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/pesquisa-satisfacao': {
      id: '/_authenticated/cliente/pesquisa-satisfacao'
      path: '/pesquisa-satisfacao'
      fullPath: '/cliente/pesquisa-satisfacao'
      preLoaderRoute: typeof AuthenticatedClientePesquisaSatisfacaoRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/horario-ramais': {
      id: '/_authenticated/cliente/horario-ramais'
      path: '/horario-ramais'
      fullPath: '/cliente/horario-ramais'
      preLoaderRoute: typeof AuthenticatedClienteHorarioRamaisRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/filas': {
      id: '/_authenticated/cliente/filas'
      path: '/filas'
      fullPath: '/cliente/filas'
      preLoaderRoute: typeof AuthenticatedClienteFilasRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/blacklist': {
      id: '/_authenticated/cliente/blacklist'
      path: '/blacklist'
      fullPath: '/cliente/blacklist'
      preLoaderRoute: typeof AuthenticatedClienteBlacklistRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/audios': {
      id: '/_authenticated/cliente/audios'
      path: '/audios'
      fullPath: '/cliente/audios'
      preLoaderRoute: typeof AuthenticatedClienteAudiosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/whitelist': {
      id: '/_authenticated/admin/whitelist'
      path: '/admin/whitelist'
      fullPath: '/admin/whitelist'
      preLoaderRoute: typeof AuthenticatedAdminWhitelistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/servidor': {
      id: '/_authenticated/admin/servidor'
      path: '/admin/servidor'
      fullPath: '/admin/servidor'
      preLoaderRoute: typeof AuthenticatedAdminServidorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blacklist': {
      id: '/_authenticated/admin/blacklist'
      path: '/admin/blacklist'
      fullPath: '/admin/blacklist'
      preLoaderRoute: typeof AuthenticatedAdminBlacklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/relatorios/uras': {
      id: '/_authenticated/cliente/relatorios/uras'
      path: '/relatorios/uras'
      fullPath: '/cliente/relatorios/uras'
      preLoaderRoute: typeof AuthenticatedClienteRelatoriosUrasRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/relatorios/pesquisa': {
      id: '/_authenticated/cliente/relatorios/pesquisa'
      path: '/relatorios/pesquisa'
      fullPath: '/cliente/relatorios/pesquisa'
      preLoaderRoute: typeof AuthenticatedClienteRelatoriosPesquisaRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/relatorios/geral': {
      id: '/_authenticated/cliente/relatorios/geral'
      path: '/relatorios/geral'
      fullPath: '/cliente/relatorios/geral'
      preLoaderRoute: typeof AuthenticatedClienteRelatoriosGeralRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/relatorios/filas': {
      id: '/_authenticated/cliente/relatorios/filas'
      path: '/relatorios/filas'
      fullPath: '/cliente/relatorios/filas'
      preLoaderRoute: typeof AuthenticatedClienteRelatoriosFilasRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/relatorios/ddd': {
      id: '/_authenticated/cliente/relatorios/ddd'
      path: '/relatorios/ddd'
      fullPath: '/cliente/relatorios/ddd'
      preLoaderRoute: typeof AuthenticatedClienteRelatoriosDddRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
  }
}

interface AuthenticatedClienteRouteChildren {
  AuthenticatedClienteAudiosRoute: typeof AuthenticatedClienteAudiosRoute
  AuthenticatedClienteBlacklistRoute: typeof AuthenticatedClienteBlacklistRoute
  AuthenticatedClienteFilasRoute: typeof AuthenticatedClienteFilasRoute
  AuthenticatedClienteHorarioRamaisRoute: typeof AuthenticatedClienteHorarioRamaisRoute
  AuthenticatedClientePesquisaSatisfacaoRoute: typeof AuthenticatedClientePesquisaSatisfacaoRoute
  AuthenticatedClienteRamaisRoute: typeof AuthenticatedClienteRamaisRoute
  AuthenticatedClienteRegraHorarioRoute: typeof AuthenticatedClienteRegraHorarioRoute
  AuthenticatedClienteRoteamentoRoute: typeof AuthenticatedClienteRoteamentoRoute
  AuthenticatedClienteTroncosRoute: typeof AuthenticatedClienteTroncosRoute
  AuthenticatedClienteUrasRoute: typeof AuthenticatedClienteUrasRoute
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
  AuthenticatedClienteRelatoriosDddRoute: typeof AuthenticatedClienteRelatoriosDddRoute
  AuthenticatedClienteRelatoriosFilasRoute: typeof AuthenticatedClienteRelatoriosFilasRoute
  AuthenticatedClienteRelatoriosGeralRoute: typeof AuthenticatedClienteRelatoriosGeralRoute
  AuthenticatedClienteRelatoriosPesquisaRoute: typeof AuthenticatedClienteRelatoriosPesquisaRoute
  AuthenticatedClienteRelatoriosUrasRoute: typeof AuthenticatedClienteRelatoriosUrasRoute
}

const AuthenticatedClienteRouteChildren: AuthenticatedClienteRouteChildren = {
  AuthenticatedClienteAudiosRoute: AuthenticatedClienteAudiosRoute,
  AuthenticatedClienteBlacklistRoute: AuthenticatedClienteBlacklistRoute,
  AuthenticatedClienteFilasRoute: AuthenticatedClienteFilasRoute,
  AuthenticatedClienteHorarioRamaisRoute:
    AuthenticatedClienteHorarioRamaisRoute,
  AuthenticatedClientePesquisaSatisfacaoRoute:
    AuthenticatedClientePesquisaSatisfacaoRoute,
  AuthenticatedClienteRamaisRoute: AuthenticatedClienteRamaisRoute,
  AuthenticatedClienteRegraHorarioRoute: AuthenticatedClienteRegraHorarioRoute,
  AuthenticatedClienteRoteamentoRoute: AuthenticatedClienteRoteamentoRoute,
  AuthenticatedClienteTroncosRoute: AuthenticatedClienteTroncosRoute,
  AuthenticatedClienteUrasRoute: AuthenticatedClienteUrasRoute,
  AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
  AuthenticatedClienteRelatoriosDddRoute:
    AuthenticatedClienteRelatoriosDddRoute,
  AuthenticatedClienteRelatoriosFilasRoute:
    AuthenticatedClienteRelatoriosFilasRoute,
  AuthenticatedClienteRelatoriosGeralRoute:
    AuthenticatedClienteRelatoriosGeralRoute,
  AuthenticatedClienteRelatoriosPesquisaRoute:
    AuthenticatedClienteRelatoriosPesquisaRoute,
  AuthenticatedClienteRelatoriosUrasRoute:
    AuthenticatedClienteRelatoriosUrasRoute,
}

const AuthenticatedClienteRouteWithChildren =
  AuthenticatedClienteRoute._addFileChildren(AuthenticatedClienteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminBlacklistRoute: typeof AuthenticatedAdminBlacklistRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminServidorRoute: typeof AuthenticatedAdminServidorRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminWhitelistRoute: typeof AuthenticatedAdminWhitelistRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClienteRoute: AuthenticatedClienteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminBlacklistRoute: AuthenticatedAdminBlacklistRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminServidorRoute: AuthenticatedAdminServidorRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminWhitelistRoute: AuthenticatedAdminWhitelistRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RamalRoute: RamalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
